### ISSUE TITLE
Issue with outbound link tracking

### ISSUE THREAD

**Issue by Poeschl** [svendroid/gridsome-plugin-plausible-analytics#2]
When using outbound link tracking script in combination with a custom domain, the script could not be found.

I compared the snipplet from the docs with the rendered script tag in the head and it seems that the path changed.

From the docs: `src="https://plausible.io/js/script.outbound-links.js` 

Rendered from this plugin: `src="https://plausible.io/js/index.outbound-links.js`

**Comment by svendroid** [comment]
@Poeschl fixed it. Should be working with version 1.2.0.
